In [ ]:
!pip install numpy

In [ ]:
import numpy as np


In [ ]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
np.ones((3,4))# to quickly create an array of ones consisting of row =3 and columns-  4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.array([[1,3,4],[5,6,8]])
print("array:\n",arr)
print("shape: ", arr.shape )
print("number of dimensions:",arr.ndim)
print("size (no of elements ):",arr.size)
print("data type ", arr.dtype)
print("item size (in bytes)",arr.itemsize)

array:
 [[1 3 4]
 [5 6 8]]
shape:  (2, 3)
number of dimensions: 2
size (no of elements ): 6
data type  int64
item size (in bytes) 8


In [ ]:
#vectorized
ar1 =np.array([1,2,3,4,5])
ar2 =np.array([4,5,6,8,9])
print("addition",ar1+ar2)
print("subtraction",ar1-ar2)
print("multiplication",ar1*ar2)
print("division",ar1/ar2)

addition [ 5  7  9 12 14]
subtraction [-3 -3 -3 -4 -4]
multiplication [ 4 10 18 32 45]
division [0.25       0.4        0.5        0.5        0.55555556]


In [ ]:
#universal functions
arry1=np.array([1,4,6,7,8])
print (np.sqrt(arr))
print (np.exp(arr))
print (np.log(arr))
print (np.sin(arr))

[[1.         1.73205081 2.        ]
 [2.23606798 2.44948974 2.82842712]]
[[2.71828183e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 2.98095799e+03]]
[[0.         1.09861229 1.38629436]
 [1.60943791 1.79175947 2.07944154]]
[[ 0.84147098  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.98935825]]


In [ ]:
#array slicing and indexing
arr = np.array([[1,3,4,6],[1,4,5,7],[4,6,73,4]])
print("array:\n",arr)

array:
 [[ 1  3  4  6]
 [ 1  4  5  7]
 [ 4  6 73  4]]


In [ ]:
arr[1][3] #accesing the array elements using indexing

7

In [ ]:
print(arr[0:2,2:])
print(arr[1:,1:3])

[[4 6]
 [5 7]]
[[ 4  5]
 [ 6 73]]


In [ ]:
arr[2,1]=7
print(arr)

[[1 3 4 6]
 [1 4 5 7]
 [4 7 7 4]]


In [ ]:
#normalization
data = np.array([1,4,5,7,8])
mean=np.mean(data)
std_dev=np.std(data)
norm=(data-mean)/std_dev
print("normalized data",norm)

normalized data [-1.63299316 -0.40824829  0.          0.81649658  1.22474487]


In [ ]:
#statistical operations
data = np.array([1,4,5,7,8,3,52,5,2])
print("mean",np.mean(data))
print("median",np.median(data))
print("standard deviation",np.std(data))
print("variance",np.var(data))

mean 9.666666666666666
median 5.0
standard deviation 15.114378731672845
variance 228.44444444444446


In [ ]:
#logical operation
data = np.array([1,4,5,7,8])
data>4
data[data>5]

array([7, 8])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
